services:
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    image: bobapp-front
    ports:
      - "80:80"
    depends_on:
      - back

  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    image: bobapp-back
    ports:
      - "8080:8080"
