name: FrontEnd CI CD

on:
  push:
    paths:
      - "front/**"
      - ".github/workflows/**"
    branches:
      - main
  pull_request:
    paths:
      - "front/**"
      - ".github/workflows/**"
    types:
      - opened
      - synchronize
      - reopened

jobs:
  frontend_test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: front

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache Node Modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        run: npm ci

      - name: Build Angular Project
        run: npm run build

      - name: Run Tests and Generate Code Coverage Report
        run: npm run test -- --no-watch --no-progress --browsers=ChromeHeadless --code-coverage

      - name: Upload Code Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: front-coverage-report
          path: front/coverage/
          overwrite: true
          if-no-files-found: error

      - name: Install SonarScanner
        run: |
          curl -sS https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.8.0.2856-linux.zip -o sonar-scanner.zip
          unzip sonar-scanner.zip
          sudo mv sonar-scanner-*/bin/sonar-scanner /usr/local/bin/

      - name: Run SonarCloud Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner \
            -Dsonar.projectKey=manuel-fami_bobApp_front \
            -Dsonar.sources=src \
            -Dsonar.tests=src \
            -Dsonar.typescript.lcov.reportPaths=coverage/lcov-report/lcov.info \
            -Dsonar.sourceEncoding=UTF-8
